services:
  postgres:
    image: postgres:16
    container_name: geiger-observatory-postgres
    environment:
      POSTGRES_DB: geiger_observatory
      POSTGRES_USER: geiger
      POSTGRES_PASSWORD: geiger
    ports:
      - "5432:5432"
    volumes:
      - geiger-observatory-postgres:/var/lib/postgresql/data

volumes:
  geiger-observatory-postgres:
