server:
  port: 8080

spring:
  application:
    name: geiger-observatory
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/geiger_observatory}
    username: ${DB_USERNAME:geiger}
    password: ${DB_PASSWORD:geiger}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  ingestion:
    interval-ms: 2000
    history-limit: 2000
  analysis:
    archive-window-minutes: 60
    threshold-cpm: 40
    min-duration-seconds: 15
  device:
#    mode: simulator
    mode: serial
    comm-port: tty.usbserial-1420
    baud-rate: 115200
    read-timeout-ms: 5000
    write-timeout-ms: 5000
    command: "<GETCPM>>"
    baseline-cpm: 18
    noise-band: 6
    spike-probability: 0.07
    spike-magnitude: 60
    test-anomaly-enabled: false
    test-anomaly-start-after-readings: 20
    test-anomaly-duration-readings: 120
    test-anomaly-cpm: 48
